### ISSUE TITLE
Passive option for event listener

### ISSUE THREAD

**Issue by linhntaim** [mercs600/vue3-perfect-scrollbar#14]
Hi you,

Please apply this

https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener#improving_scrolling_performance_with_passive_listeners

to prevent the warning:

`[Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952`

![image](https://user-images.githubusercontent.com/6326961/176851279-4c94a80c-4489-4f12-b7c7-20f4358041c9.png)

Thanks

**Comment by hermesalvesbr** [comment]
Any news about this warning-fix?

**Comment by devahmetkaradeniz** [comment]
Hi, I'm still receiving this warning. Is there any update on this issue?

**Comment by mercs600** [comment]
Guys, this repository and plugin serve as a wrapper for Perfect Scrollbar in Vue.js applications. 
Therefore, any bugs related to the core of the Perfect Scrollbar library should be reported here: https://perfectscrollbar.com/
