### ISSUE TITLE
This package breaks hot reload

### ISSUE THREAD

**Issue by fly3110** [mercs600/vue3-perfect-scrollbar#4]
Steps to reproduce:

Install vue/cli: `yarn global add @vue/cli`
Create a new vue app: `vue create test`
Run `vue-cli-service serve` and check that hot reload works with no issues

Add vue3-perfect-scrollbar: `yarn add vue3-perfect-scrollbar`
Add `import PerfectScrollbar from 'vue3-perfect-scrollbar'` to `main.js`
Run `vue-cli-service serve` and see that hot reload no longer work

**Comment by sagardspeed2** [comment]
@fly3110 I have same problem in vue3, Looking for the solution. Thanks for creating issue here.

**Comment by chirag-vaghasiya-micra** [comment]
@fly3110 I also have the same problem, due to this I suffered a lot. after every changes I need to refresh the page like PHP.

**Comment by fly3110** [comment]
As a workaround, I put `import PerfectScrollbar from 'vue3-perfect-scrollbar` to the very first line, before `import {...}  from 'vue'`

**Comment by mercs600** [comment]
Hi guys, thank you for let me know, this plugin was created by community. I will find some time in a few days to reproduce and fix it.

**Comment by mercs600** [comment]
@fly3110 i see the issue, for some reasons vue use umd file, but in classic way it should take esm. For now as a workaround please setup it this way:
```js
import PerfectScrollbar from 'vue3-perfect-scrollbar/dist/vue3-perfect-scrollbar.esm'
```

**Comment by jd-0001** [comment]
Is this resolved?

**Comment by BasBuur** [comment]
This is still an issue. @mercs600 's workaround fixes the issue. Still should be addressed, it took me many hours to find this package was the issue.

**Comment by mercs600** [comment]
Issue was fixed
